import React from 'react';
import back from '../components/images/back.png';

const AuthComponent = () => {
  return (
    <div className="bg-cover bg-center h-screen flex items-center justify-center" style={{ backgroundImage: `url(${back})` }}>
      <div className="flex flex-col items-center justify-center w-96 p-8 gap-4 rounded-md border-1 border-solid border-purple-600 bg-white shadow-md">
        <div className="flex items-center mb-4">
          <img src="https://staging-internal.d1nwfechdidmfz.amplifyapp.com/_next/static/media/hifiLogo.6b03b00d.svg" alt="Logo" className="mr-2" />
          <h1 className="text-3xl font-bold">HiFi Pay</h1>
        </div>
        <p className="mb-4 text-gray-600">To continue, please enter the 6-digit verification code generated by your authentication app.</p>
        <div className="flex items-center mb-4">
          {[...Array(6)].map((_, index) => (
            <React.Fragment key={index}>
              <input type="text" maxLength="1" className={`w-12 p-2 border border-gray-300 text-center ${index === 0 ? 'rounded-l-lg' : index === 5 ? 'rounded-r-lg' : ''}`} />
              {index === 2 && <div className="w-4 h-8 border-t border-b border-gray-300 mx-2"></div>}
            </React.Fragment>
          ))}
        </div>
        <button className="bg-purple-600 text-white py-2 px-6 rounded-md mb-2">Confirm</button>
        <p className="text-purple-800 underline">Use another authentication method</p>
        <p className="text-purple-800 underline">Need help authenticating?</p>
      </div>
    </div>
  );
};

export default AuthComponent;
